config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users do
    collection do
      resource :search, only: %i[show]
    end
  end
  resource :authentication, only: %i[new create destroy]
  get 'home', to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/paginable.rb
module Paginable
  extend ActiveSupport::Concern
  DEFAULT_PAGE = 0
  DEFAULT_PER_PAGE = 25
  included do
    cattr_accessor :per_page
    self.per_page = DEFAULT_PER_PAGE

    class << self
      def page(pap = DEFAULT_PAGE)
        offset((pap || DEFAULT_PAGE).to_i * per_page + 1).limit(per_page)
      end

      def per(num = DEFAULT_PER_PAGE)
        limit(num)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Paginable
  has_secure_password
  # TODO: implement my all design
  acts_as_tree parent_column_name: :manager_id

  belongs_to :manager, class_name: User.name, optional: true
  has_many :employees, foreign_key: :manager_id, class_name: User.name

  validates :username, presence: true, uniqueness: true
  validates :employees_count, numericality: {
                                only_integer: true,
                                less_than_or_equal_to: 10
                              }

  scope :needed_fields, -> { select(:id, :name, :username, :manager_id) }

  after_create  :increment_counter_cache
  after_destroy :decrement_counter_cache

  def self.search(keyword)
    where('username iLIKE ? OR name iLIKE ?', "%#{keyword}%", "%#{keyword}%")
  end

  def ordered_ancestors
    self.class.where(id: self_and_ancestors_ids)
  end

  def showing_name
    name || username
  end

  private

  def decrement_counter_cache
    self.class.decrement_counter('employees_count', manager_id)
  end

  def increment_counter_cache
    self.class.increment_counter('employees_count', manager_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthenticationHelper
  before_action :authenticate_user!

  private

  def authenticate_user!
    return if logged_in?

    store_location
    redirect_to new_authentication_path, alert: 'Please login to continue'
  end

  def unauthenticate_user!
    return unless logged_in?

    redirect_to root_path, alert: 'Your account is already logged in'
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_action :authenticate_user!, except: %i[destroy]
  before_action :unauthenticate_user!, only: :new

  def new
    @authentication = Authentication.new
  end

  def create
    @authentication = Authentication.new(authentication_params)
    if @authentication.save
      log_in(@authentication.user)
      redirect_back_or root_path, notice: t('.success')
    else
      flash[:alert] = @authentication.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path, notice: t('.logged_out')
  end

  private

  def authentication_params
    params.require(:authentication).permit(:username, :password)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    #TODO: fix n + 1
    @users = User.includes(:employees).needed_fields
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  DEFAULT_PER_PAGE = 10

  def show
    @users = User.needed_fields.search(params[:q])

    respond_to do |format|
      format.html
      format.json { render json: @users.limit(DEFAULT_PER_PAGE) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def index
    @index = UsersOperations::Index.new(params)
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def edit; end

  def show
    @user = UserPresenter.new(User.find_by(id: params[:id]) || current_user)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: t('.success')
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('.success')
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :title, :name, :username, :manager_id, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parse_tree_elements(data)
    elements = '<ul>'

    data.each do |record, children|
      elements += <<-HTML.strip
        <li>
          <a href=#{user_path(record)}> #{record.name || record.username} </a>
          #{parse_tree_elements(children) if children.present?}
        </li>
      HTML
    end

    elements += '</ul>'
    elements.html_safe
  end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
  #Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.is_a? User
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default, options = {})
    redirecting_url = session[:forwarding_url] || default
    redirect_to(redirecting_url, options)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/new.html.haml
.columns.is-mobile
  = form_for @authentication, url: authentication_path, html: { class: 'column is-half is-offset-one-quarter'} do |f|
    %div.field
      = f.label :username, class: 'label'
      .control
        = f.text_field :username, class: 'input'
    %div.field
      = f.label :password, class: 'label'
      .control
        = f.password_field :password, class: 'input'
    %div.control
      = f.submit "Signup/Login", class: 'button is-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AwsomeHr
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    = render 'shared/flash'
    = yield

app/views/pages/home.html.haml
.tree
  %ul
    = render @users

app/views/shared/_flash.html.haml
.c-notification
  - if notice.present?
    = notice
  - if alert.present?
    = alert

app/views/shared/_header.html.haml
%nav.navbar{"aria-label" => "main navigation", :role => "navigation"}
  .navbar-brand
    %a.navbar-item.title{:href => root_path}
      Awsome HR
    %a.navbar-burger.burger{"aria-expanded" => "false", "aria-label" => "menu", "data-target" => "navbarBasicExample", :role => "button"}
      %span{"aria-hidden" => "true"}
      %span{"aria-hidden" => "true"}
      %span{"aria-hidden" => "true"}
  .navbar-menu
    - if logged_in?
      .navbar-start
        .navbar-item.has-dropdown.is-hoverable
          %a.navbar-link.subtitle.is-5
            = current_user.name || current_user.username
          .navbar-dropdown
            = link_to 'Profile', current_user, class: 'navbar-item'
            = link_to 'Logout', authentication_path, method: :delete, class: 'navbar-item'
    .navbar-end
      - if logged_in?
        .navbar-item
          .buttons
            = link_to 'New user', new_user_path,  class: 'button is-primary'
      - else
        .navbar-item
          .buttons
            = link_to 'Login/Sign up', new_authentication_path, class: 'button is-primary'

app/views/users/_form.html.haml
.columns.is-mobile
  .column.is-half.is-offset-one-quarter
    %h1.title= (@user.new_record? ? 'Create' : 'Edit') + ' User'
    = form_for @user, html: {class: 'form'} do |f|
      %div.field
        = f.label :name, class: 'label'
        .control
          = f.text_field :name, autofocus: true, class: 'input'
      %div.field
        = f.label :title, class: 'label'
        .control
          = f.text_field :title, class: 'input'
      %div.field
        = f.label :username, class: 'label'
        .control
          = f.text_field :username, class: 'input'
      %div.field
        = f.label :manager, class: 'label'
        .control
          = f.select :manager_id, [], {}, { class: 'js-users__users-selector select input p-10'}
      %div.field
        = f.label :password, class: 'label'
        .control
          = f.password_field :password, class: 'input'
      %div
        = f.label :password_confirmation, class: 'label'
        .control
          = f.password_field :password_confirmation, class: 'input'
      %div
        = f.submit 'Save', class: 'button is-info mt-10'

= javascript_pack_tag 'users/form'

app/views/users/_search_form.html.haml
.columns.is-mobile
  %form.column.is-half.is-offset-one-quarter
    .columns.is_mobile
      .column
        .field
          .control
            .select
              = select_tag :type, options_for_select(UsersOperations::Index::TYPES, params[:type]), {class: 'js-users__types-selector'}
      .column.js-users__comparing-user{class: "#{'is-hidden' if params[:type] != UsersOperations::Index::REATIONSHIP_CHECK}"}
        .field
          .control
            = select_tag :user1, [], { class: 'js-users__users-selector p-10', required: params[:type] == UsersOperations::Index::REATIONSHIP_CHECK}
      .column.js-users__comparing-user{class: "#{'is-hidden' if params[:type] != UsersOperations::Index::REATIONSHIP_CHECK}"}
        .field
          .control
            = select_tag :user2, [], { class: 'js-users__users-selector p-10', required: params[:type] == UsersOperations::Index::REATIONSHIP_CHECK}
      .column.js-users__single-select{class: "#{'is-hidden' unless [UsersOperations::Index::EMPLOYEE_SEARCH, UsersOperations::Index::MANAGER_SEARCH, nil].include? params[:type]}"}
        .field
          .control
            = select_tag :user, [], { class: 'js-users__users-selector p-10', required: [UsersOperations::Index::EMPLOYEE_SEARCH, UsersOperations::Index::MANAGER_SEARCH, nil].include?(params[:type])}
      .column.js-users_normal-input{class: "#{'is-hidden' if params[:type] != UsersOperations::Index::SHOW_WITH_LIMIT}"}
        .field
          .control
            %input.input{:placeholder => 'Enter per page', name: :per_page, value: params[:per_page] || User.per_page, type: :number}
      .column.js-users_normal-input{class: "#{'is-hidden' if params[:type] != UsersOperations::Index::SHOW_WITH_LIMIT}"}
        .field
          .control
            %input.input{:placeholder => 'Enter page', name: :page, value: params[:page], type: :number}
      .column
        .control
          %button.button.is-info
            Search

app/views/users/_user.html.haml
%li
  = link_to user.name || user.username, user
  - if user.employees.present?
    %ul
      = render user.employees

app/views/users/edit.html.haml
= render 'form'

app/views/users/index.html.haml
= render 'search_form'
%h3.has-text-centered.mt-5.title
  Orgainisation chart
  - if params[:type] == UsersOperations::Index::SHOW_WITH_LIMIT || params[:type].blank?
    = "(Showing #{params[:per_page] || User::DEFAULT_PER_PAGE} nodes)"
- if params[:type] == UsersOperations::Index::REATIONSHIP_CHECK
  %h5.title.has-text-centered
    = @index.user1.showing_name
    -
    = @index.records
    -
    = @index.user2.showing_name
- else
  .tree
    = parse_tree_elements @index.records.hash_tree

= javascript_pack_tag 'users'

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
.container.c-users__show
  %h4.title
    %strong Title:
    = @user.title
  %h4.subtitle
    %strong Name:
    = @user.name
  %h4.subtitle
    %strong Username:
    = @user.username
  .buttons
    = link_to 'Edit', [:edit, @user],  class: 'button is-primary'
  %h5.has-text-centered.mt-5.title Orgainisation chart
  .tree
    = parse_tree_elements @user.descendants
  %h5.has-text-centered.mt-5.title Manager charts
  .tree
    = parse_tree_elements @user.ancestors